---
title: "Team TAM COVID-19 Dashboard "
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```
Student info
=====================================  
Column {data-width=450}
-----------------------------------------------------------------------

### Stress busters

```{r}
dt1 <-read.csv("COVID-19 Survey Student Responses.csv")
#dt1

attach(dt1)
# barplot(table(Stress.busters),las=2)

# Preprocessing the Data
a<- data.frame(table(Stress.busters))
b<- a[a$Freq>2,]

# Plotting the Data
library(ggplot2)
ggplot(b, aes(x = Stress.busters, y = Freq)) +
  geom_col(fill = "#0099f9") +
  labs(
    x = "Stress Busters",
    y = "Frequency"
  ) +
  theme(
    axis.title.x = element_text(color = "#0099f9", size = 15, face = "bold"),
    axis.title.y = element_text(size = 15, face = "italic"),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)
  )

```



### Covids effect on peoples health

```{r}

library(ggplot2)
library(tidyverse)
library(ggpubr)
effectDF <- read.csv("PersonalityEffectsDueToCovid.csv")


#barplot
ggplot(effectDF,
       aes(X14..Overall.covid.has.changed.you.in.which.manner., 
           fill = HealthIssues))+
  geom_bar()+
  labs(x="Covid's Effect on people")+
  theme_minimal()+scale_fill_brewer(palette = "Pastel1")

```


Column {.tabset}
-----------------------------------------------------------------------

### Family relations heatmap

```{r}

library(dplyr)

effectDF = read.csv("PersonalityEffectsDueToCovid.csv")

df_grouped = effectDF %>% dplyr::count(X8..Relations.with.family.have.improved., 
                                X9..Contact.with.old.school.friends.or.fellow.mates.have.increased.and.social.life.have.improved.after.covid)
colnames(df_grouped) <- c("FamilyRelations","ContactWithOldFriends","Num")
#View(df_grouped)

ggplot(df_grouped,aes(FamilyRelations,ContactWithOldFriends,fill=Num))+
  geom_tile() +
  scale_fill_distiller(palette = "RdPu")


```


### WRT. student change in weight,health issues,number of meals

```{r}


dt2 <- data.frame(read.csv("COVID-19 Survey Student Responses.csv"))
attach(dt2)

par(mfrow=c(1,3))
pie(table(dt2$Change.in.your.weight))
pie(table(dt2$Health.issue.during.lockdown))
pie(table(dt2$Number.of.meals.per.day))

```


### Device and online class rating

```{r}
dt2 <- data.frame(read.csv("COVID-19 Survey Student Responses.csv"))
attach(dt2)

d<- data.frame(table(dt2$Rating.of.Online.Class.experience,dt2$Medium.for.online.class))
#d

library(ggplot2)
library(hrbrthemes)
library(plotly)

x <- d$Var1
y <- d$Var2
data <- data.frame(d$Var1,d$Var2,d$Freq)

data <- data %>% mutate(text = paste0("x: ", x, "\n", "y: ", y, "\n", "Value: ",d$Freq))
p <- ggplot(data, aes(x, y, fill= d$Freq, text=text)) + geom_tile() + theme_ipsum()

ggplotly(p, tooltip="text")

```

Mental Health Info {data-orientation=rows}
=====================================

Row {.tabset-fade .tabset}
-------------------------------------

### Age based online rating

```{r}

dt2 <- data.frame(read.csv("COVID-19 Survey Student Responses.csv"))
attach(dt2)

d1 <- matrix(table(data.frame(dt2[dt2$Age.of.Subject<18,"Rating.of.Online.Class.experience"])),nrow=1)
d2 <- matrix(table(data.frame(dt2[dt2$Age.of.Subject>=18 && dt2$Age.of.Subject<30,"Rating.of.Online.Class.experience"])),nrow=1)
d3 <- matrix(table(data.frame(dt2[dt2$Age.of.Subject>30,"Rating.of.Online.Class.experience"])),nrow=1)

library(plotly)

labels = c("Age<18","Age<18,30>","Age>30","Average","Excellent","Good","Poor","Very poor","Average","Excellent","Good","Poor","Very poor","Average","Excellent","Good","Poor","Very poor")
parents = c("","","","Age<18","Age<18","Age<18","Age<18","Age<18","Age<18,30>","Age<18,30>","Age<18,30>","Age<18,30>","Age<18,30>","Age>30","Age>30","Age>30","Age>30","Age>30")
values <- c(1,1,1,d1,d2,d3)

fig <- plot_ly(
  type="treemap",
  labels=labels,
  parents=parents,
  values=values,
  marker=list(colors=c("#FF0000", "#FF4D4D", "#FF9999", "#FFCCCC", "#FFE6E6", "lightgray", "lightblue","#000", "royalblue", "lightgray", "purple", "#FFF","#000", "royalblue","#23456")))

fig


```



### What do you miss the most

```{r}

dt2 <- data.frame(read.csv("COVID-19 Survey Student Responses.csv"))
attach(dt2)
a<- data.frame(table(What.you.miss.the.most))
b<- a[a$Freq>10,]
c<- a[a$Freq<10,]
others<- sum(c$Freq)

#c(b$Freq,others)
x<- c(b$What.you.miss.the.most)

library(tidyverse)
data <- data.frame(
  id=seq(1,8),
  individual=c("Collegues","Eating outside","Friends,relative","Nothing","Roaming around freely","School/college","Travelling","Others"),
  value=c(b$Freq,others)
)
label_data <- data
number_of_bar <- nrow(label_data)
angle <-  90 - 360 * (label_data$id-0.5) /number_of_bar     
label_data$hjust<-ifelse( angle < -90, 1, 0)
label_data$angle<-ifelse(angle < -90, angle+180, angle)
p <- ggplot(data, aes(x=as.factor(id), y=value)) +      
  geom_bar(stat="identity", fill=alpha("skyblue", 0.7)) +
  ylim(-100,400) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")   
  ) +
  coord_polar(start = 0) +
  geom_text(data=label_data, aes(x=id, y=value+10, label=individual, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE ) 
p

```


### Country wise analysis of Mental health terms

```{r}

searchterms = readxl::read_excel("SearchTermsMerged.xlsx")

total<- ggplot(searchterms,aes(x=Week,y=totalTerms, fill=Country))+geom_area()+ggtitle("Total")
dep <- ggplot(searchterms,aes(x=Week,y=depression, fill=Country))+geom_area()+ggtitle("Depression")
anx <- ggplot(searchterms,aes(x=Week,y=anxiety, fill=Country))+geom_area()+ggtitle("Anxiety")
insom <- ggplot(searchterms,aes(x=Week,y=insomnia, fill=Country))+geom_area()+ggtitle("Insomnia")
ggarrange(total,dep,anx,insom,nrow=2,ncol=2)
```

### Health issues encountered by different strata of people

```{r}
library(ggplot2)
library(tidyverse)
library(ggpubr)

effectDF=read.csv("PersonalityEffectsDueToCovid.csv")

#DonutChart HealthIssues(grad+woking)
effectDF.HealthIssues = effectDF %>% 
  filter(You..are.a. == "graduate" | You..are.a. == "working" ) %>% 
  group_by(HealthIssues) %>% 
  count() %>% 
  ungroup()%>% 
  arrange(desc(HealthIssues)) %>%
  mutate(percentage = round(n/sum(n),4)*100,
         lab.pos = cumsum(percentage)-.5*percentage)

gw<-ggplot(data = effectDF.HealthIssues, 
       aes(x = 2, y = percentage, fill =HealthIssues ))+
  geom_bar(stat = "identity")+
  coord_polar("y", start = 200) +
  geom_text(aes(y = lab.pos, label = paste(percentage,"%", sep = "")), col = "black") +
  theme_void() +
  ggtitle("Working people")+
  scale_fill_brewer(palette = "Set3")+
  xlim(.2,2.5)

#DonutChart HealthIssues(College Student)
effectDF.HealthIssues2 = effectDF %>% 
  filter(You..are.a. == "college student") %>% 
  group_by(HealthIssues) %>% 
  count() %>% 
  ungroup()%>% 
  arrange(desc(HealthIssues)) %>%
  mutate(percentage = round(n/sum(n),4)*100,
         lab.pos = cumsum(percentage)-.5*percentage)

cs<-ggplot(data = effectDF.HealthIssues2, 
       aes(x = 2, y = percentage, fill =HealthIssues ))+
  geom_bar(stat = "identity")+
  coord_polar("y", start = 200) +
  geom_text(aes(y = lab.pos, label = paste(percentage,"%", sep = "")), col = "black") +
  theme_void() +
  ggtitle("College students")+
  scale_fill_brewer(palette = "Pastel2")+
  xlim(.2,2.5)

#DonutChart HealthIssues(School Student)
effectDF.HealthIssues3 = effectDF %>% 
  filter(You..are.a. == "school student") %>% 
  group_by(HealthIssues) %>% 
  count() %>% 
  ungroup()%>% 
  arrange(desc(HealthIssues)) %>%
  mutate(percentage = round(n/sum(n),4)*100,
         lab.pos = cumsum(percentage)-.5*percentage)

ss<-ggplot(data = effectDF.HealthIssues3, 
       aes(x = 2, y = percentage, fill =HealthIssues ))+
  geom_bar(stat = "identity")+
  coord_polar("y", start = 200) +
  geom_text(aes(y = lab.pos, label = paste(percentage,"%", sep = "")), col = "black") +
  theme_void() +
  ggtitle("School students")+
  scale_fill_brewer(palette = "Pastel1")+
  xlim(.2,2.5)
ggarrange(gw,cs,ss,nrow=3,ncol=1)
```


### Age wise social media trends

```{r}


dt2 <- data.frame(read.csv("COVID-19 Survey Student Responses.csv"))
attach(dt2)

d1 <- data.frame(table(data.frame(dt2[dt2$Age.of.Subject<18,"Prefered.social.media.platform"])))
d2 <- data.frame(table(data.frame(dt2[dt2$Age.of.Subject>=18 && dt2$Age.of.Subject<30,"Prefered.social.media.platform"])))
d3 <- data.frame(table(data.frame(dt2[dt2$Age.of.Subject>30,"Prefered.social.media.platform"])))

df1<- data.frame(d1 %>% filter(Var1 == "Facebook" | Var1 == "Instagram" | Var1 == "Youtube" | Var1 == "Whatsapp" | Var1 == "None"))
df2<- data.frame(d2 %>% filter(Var1 == "Facebook" | Var1 == "Instagram" | Var1 == "Youtube" | Var1 == "Whatsapp" | Var1 == "None"))
df3<- data.frame(d3 %>% filter(Var1 == "Facebook" | Var1 == "Instagram" | Var1 == "Youtube" | Var1 == "Whatsapp" | Var1 == "None"))

d1<- matrix(df1[,c("Freq")],byrow = TRUE)
d2<- matrix(df2[,c("Freq")],byrow = TRUE)
d3<- matrix(df3[,c("Freq")],byrow = TRUE)

library(fmsb)
set.seed(999)
data <- as.data.frame(matrix(c(d1,d2,d3),nrow = 3,ncol=5,byrow = TRUE))
colnames(data) <- c("Facebook" , "Instagram" , "None" , "Whatsapp" , "Youtube" )
rownames(data) <- c("Age<18","Age<18,30>","Age>30")

data <- rbind(rep(360,5) , rep(0,5) , data)

library(RColorBrewer)
coul <- brewer.pal(3, "Dark2")
colors_border <- coul
library(scales)
colors_in <- alpha(coul,0.3)

radarchart( data  , axistype=1 , 
            pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
            cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,400,100), cglwd=0.8,
            vlcex=0.8 
)
legend(x=0.7, y=1, legend = rownames(data[-c(1,2),]), bty = "n", pch=20 , col=colors_in , text.col = "grey", cex=1.2, pt.cex=3)

```

Row {data-height=400}
-------------------------------------
### Time spent on each activity

```{r}

dt2 <- read.csv("COVID-19 Survey Student Responses.csv")
#dt2
attach(dt2)

Classes <- Time.spent.on.Online.Class
Study <- Time.spent.on.self.study
Fitness <- Time.spent.on.fitness
Sleep <- Time.spent.on.sleep
Social_media <- Time.spent.on.social.media

a<- data.frame(Classes,Study, Fitness, Sleep, Social_media)
boxplot(a, col = c("#B4E197","#FFD59E","#95D1CC","#E4E9BE","#8D8DAA"))

```


### Wordcloud for Stress relieving activities

```{r}

words=df[,c("Stress.busters")]
#words
write.table(words, file = "my_data.txt")
library("tm")
#library("tmap")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
text <- readLines(file("my_data.txt"))
docs <- Corpus(VectorSource(text))
#inspect(docs)
#Replacing “/”, “@” and “|” with space:
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
docs <- tm_map(docs, removeWords, c("blabla1", "blabla2")) 
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
#head(d, 10)
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0, 
          colors=brewer.pal(8, "Dark2"))


```